name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [18]

    steps:
      - name: 1. 读取仓库
        uses: actions/checkout@v3

      - name: 2. 准备 Node.js 环境
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # Windows 专用构建支持
      - name: 2.1 安装 Python
        if: matrix.os == 'windows-latest'
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: 2.2 安装 MSBuild
        if: matrix.os == 'windows-latest'
        uses: microsoft/setup-msbuild@v1.3.1

      # 重要：先安装依赖，但跳过 preinstall 脚本（避免触发 node-gyp-build）
      - name: 3. 安装依赖（跳过 node-gyp-build）
        run: npm install --ignore-scripts

      # 然后手动 rebuild serialport
      - name: 3.1 重新构建 serialport 模块
        if: matrix.os == 'windows-latest'
        run: npx electron-rebuild -f -w @serialport/bindings-cpp

      - name: 4. Linux 打包
        if: matrix.os == 'ubuntu-latest'
        run: |
          npm run electron:linux-build --linux
        env:
          GH_TOKEN: ${{ secrets.SHKJ_CLIENT_RELEASE_TOKEN }}

      - name: 4. Windows 打包
        if: matrix.os == 'windows-latest'
        run: |
          npm run electron:win-build --win
        env:
          GH_TOKEN: ${{ secrets.SHKJ_CLIENT_RELEASE_TOKEN }}

      - name: 5. 创建 Release 草稿
        run: gh release create ${{ github.ref_name }} --draft
        env:
          GH_TOKEN: ${{ secrets.SHKJ_CLIENT_RELEASE_TOKEN }}

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: 1. 读取仓库
        uses: actions/checkout@v3

      - name: 2. 发布正式 Release
        run: gh release edit ${{ github.ref_name }} --draft=false
        env:
          GH_TOKEN: ${{ secrets.SHKJ_CLIENT_RELEASE_TOKEN }}
